# Generated by Django 5.2.4 on 2025-08-29 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('dashboard', 'Dashboard'), ('productos', 'Productos'), ('proveedores', 'Proveedores'), ('clientes', 'Clientes'), ('facturas', 'Facturas'), ('pagos', 'Pagos'), ('stock', 'Stock'), ('caja', 'Control de Caja'), ('reportes', 'Reportes'), ('configuracion', 'Configuración'), ('notificaciones', 'Notificaciones')], max_length=20)),
                ('puede_ver', models.BooleanField(default=True)),
                ('puede_crear', models.BooleanField(default=False)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuario',
                'ordering': ['usuario', 'modulo'],
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
