# Generated by Django 5.2.4 on 2025-08-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_permisousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisousuario',
            name='modulo',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('productos', 'Productos'), ('proveedores', 'Proveedores'), ('clientes', 'Clientes'), ('facturas_venta', 'Facturas de Venta'), ('facturas_compra', 'Facturas de Compra'), ('pagos', 'Pagos'), ('stock', 'Stock'), ('caja', 'Control de Caja'), ('reportes', 'Reportes'), ('configuracion', 'Configuración'), ('notificaciones', 'Notificaciones')], max_length=20),
        ),
    ]
