# Generated by Django 5.2.4 on 2025-08-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movimientostock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='categoria',
            field=models.CharField(choices=[('general', 'General'), ('alertas', 'Alertas'), ('email', 'Email'), ('stock', 'Stock'), ('facturacion', 'Facturación'), ('tema', 'Tema Visual')], default='general', max_length=20),
        ),
    ]
