# Generated by Django 5.2.4 on 2025-08-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_observacion_from_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuscripcionPush',
        ),
    ]
