# Generated by Django 5.2.4 on 2025-12-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_ciudad_cliente_estado_cliente_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observaciones',
        ),
    ]
