# Generated by Django 5.2.4 on 2025-08-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_suscripcion_push'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='monto',
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_total',
            field=models.IntegerField(default=0, help_text='Monto total del pago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='observacion',
            field=models.TextField(blank=True, help_text='Observaciones adicionales del pago', null=True),
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(help_text='Monto asignado de este pago a esta factura')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_facturas', to='core.factura')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_facturas', to='core.pago')),
            ],
            options={
                'verbose_name': 'Asignación de Pago a Factura',
                'verbose_name_plural': 'Asignaciones de Pagos a Facturas',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('pago', 'factura')},
            },
        ),
    ]
