# Generated by Django 5.2.4 on 2025-08-05 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pago_factura_remove_pago_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente que realiza el pago', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor al que se realiza el pago', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.proveedor'),
        ),
    ]
