# Generated by Django 5.2.4 on 2025-08-12 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pago_cliente_pago_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('saldo_inicial', models.IntegerField(default=0)),
                ('saldo_final', models.IntegerField(default=0)),
                ('saldo_real', models.IntegerField(default=0)),
                ('diferencia', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_aperturadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('combustible', 'Combustible'), ('mantenimiento', 'Mantenimiento'), ('servicios', 'Servicios'), ('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('utiles', 'Útiles de Oficina'), ('limpieza', 'Limpieza'), ('seguridad', 'Seguridad'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.IntegerField()),
                ('comprobante', models.CharField(blank=True, help_text='Número de factura, recibo, etc.', max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='core.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('categoria', models.CharField(choices=[('venta', 'Venta'), ('pago_proveedor', 'Pago a Proveedor'), ('gasto', 'Gasto'), ('retiro', 'Retiro'), ('deposito', 'Depósito'), ('ajuste', 'Ajuste'), ('otro', 'Otro')], max_length=20)),
                ('monto', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('referencia', models.CharField(blank=True, help_text='Número de factura, recibo, etc.', max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
