# Generated by Django 5.2.4 on 2025-08-12 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_caja_gasto_movimientocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(100000, '100.000 Gs.'), (50000, '50.000 Gs.'), (20000, '20.000 Gs.'), (10000, '10.000 Gs.'), (5000, '5.000 Gs.'), (2000, '2.000 Gs.'), (1000, '1.000 Gs.'), (500, '500 Gs.'), (100, '100 Gs.'), (50, '50 Gs.'), (25, '25 Gs.'), (10, '10 Gs.'), (5, '5 Gs.'), (1, '1 Gs.')])),
                ('cantidad', models.IntegerField(default=0)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominaciones', to='core.caja')),
            ],
            options={
                'verbose_name': 'Denominación',
                'verbose_name_plural': 'Denominaciones',
                'ordering': ['-valor'],
                'unique_together': {('valor', 'caja')},
            },
        ),
    ]
