# Generated by Django 5.2.4 on 2025-08-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_denominacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denominacion',
            name='valor',
            field=models.IntegerField(choices=[(100000, '100.000 Gs.'), (50000, '50.000 Gs.'), (20000, '20.000 Gs.'), (10000, '10.000 Gs.'), (5000, '5.000 Gs.'), (2000, '2.000 Gs.'), (1000, '1.000 Gs.'), (500, '500 Gs.'), (100, '100 Gs.'), (50, '50 Gs.')]),
        ),
    ]
