# Generated by Django 5.2.4 on 2025-08-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_denominacion_valor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='denominacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='denominacion',
            name='es_cierre',
            field=models.BooleanField(default=False, help_text='Indica si es denominación de cierre'),
        ),
        migrations.AlterUniqueTogether(
            name='denominacion',
            unique_together={('valor', 'caja', 'es_cierre')},
        ),
    ]
