# Generated by Django 5.2.4 on 2025-08-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_denominacion_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='rif',
            new_name='ruc',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='rif',
            new_name='ruc',
        ),
    ]
